[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw.bat'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'
rev = '503e03fdf1485e8f54cbe76d09bf608fcde29107'
hook_add = '''
    source ~/.vim/settings/unite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python = 
        \ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

    let g:neocomplete#force_omni_input_patterns.typescript = '[^. \t]\.\w*'
    let g:neocomplete#force_omni_input_patterns.javascript = '[^. \t]\.\w*'
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_source = '''
    let g:vimfiler_as_default_explorer = 1
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
hook_add = '''
    let g:precious_enable_switchers = {
    \   "*" : { "setfiletype" : 0 },
    \   "toml" : { "setfiletype" : 1 },
    \   "html" : { "setfiletype" : 1 },
    \   "markdown" : { "setfiletype" : 1 }
    \}
'''

[[plugins]]
repo = 'tyru/restart.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'thinca/vim-quickrun.git'

[[plugins]]
repo = 'osyo-manga/unite-filters-collection'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
    let g:lexima_enable_basic_rules = 1
    call lexima#add_rule({'char': '(', 'at': '\%#\w'})
    call lexima#add_rule({'char': '[', 'at': '\%#\w'})
    call lexima#add_rule({'char': '"', 'at': '\%#\w'})
    call lexima#add_rule({'char': "'", 'at': '\%#\w'})
    call lexima#add_rule({'char': '`', 'at': '\%#\w'})
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-scripts/fcitx.vim'
if = '''!dein#util#_is_windows()'''

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
if = '''has('gui')'''
hook_add = '''
    let g:lightline = {
        \   'colorscheme': 'jellybeans',
        \   'active': {
        \     'left': [['mode', 'paste'], ['readonly', 'filename', 'modified', 'fugitive']]
        \   },
        \   'component': {
        \     'readonly': '%{&readonly ? "\u2B64" : ""}',
        \     'fugitive': '%{exists("*fugitive#head") && fugitive#head() != "" ? "\u2B60 " . fugitive#head() : ""}',
        \   },
        \   'component_visible_condition': {
        \     'readonly': '(&readonly)',
        \     'fugitive': '(exists("*fugitive#head") && fugitive#head() != "")',
        \   },
        \   'separator': { 'left': "\u2b80", 'right': "\u2b82" },
        \   'subseparator': { 'left': "\u2b81", 'right': "\u2b83" },
        \ }
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'
if = '''has('gui')'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'digitaltoad/vim-pug'

