[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = [ 'python', 'ruby', 'vim', 'go', 'javascript', 'typescript', 'html' ]
hook_source = '''
  let g:syntastic_python_checkers = ['pyflakes']
  let g:syntastic_javascript_checkers = ['eslint']
  let g:syntastic_typescript_checkers = ['tslint', 'tsuquyomi']
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 0
  let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'vim-scripts/Python-Syntax-Folding'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
  let g:jedi#force_py_version = 3
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = 'javascript'
build = 'npm install'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'wonderful-panda/tsuquyomi'
on_ft = 'typescript'
hook_source = '''
    let g:tsuquyomi_disable_quickfix = 1
'''

[[plugins]]
repo = 'cohama/agit.vim'
on_cmd = ['Agit', 'AgitFile']

[[plugins]]
repo = 'Blackrush/vim-gocode'
on_ft = 'go'

[[plugins]]
repo = 'wonderful-panda/desertfox.vim'
on_ft = 'rst'

